//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.28 at 02:33:06 PM CEST 
//

package org.apache.cxf.fediz.core.config;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for federationProtocolType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="federationProtocolType">
 *   &lt;complexContent>
 *     &lt;extension base="{}protocolType">
 *       &lt;sequence>
 *         &lt;element ref="{}realm"/>
 *         &lt;element ref="{}issuer"/>
 *         &lt;element ref="{}roleDelimiter"/>
 *         &lt;element ref="{}roleURI"/>
 *         &lt;element ref="{}authenticationType"/>
 *         &lt;element ref="{}homeRealm"/>
 *         &lt;element ref="{}freshness"/>
 *         &lt;element ref="{}reply"/>
 *         &lt;element ref="{}request"/>
 *         &lt;element ref="{}claimTypesRequested"/>
 *         &lt;sequence maxOccurs="unbounded">
 *           &lt;element ref="{}securityTokenValidators"/>
 *         &lt;/sequence>
 *       &lt;/sequence>
 *       &lt;attribute name="version" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "federationProtocolType", propOrder = { "realm", "issuer",
        "roleDelimiter", "roleURI", "authenticationType", "homeRealm",
        "freshness", "reply", "request", "claimTypesRequested",
        "securityTokenValidators" })
public class FederationProtocolType extends ProtocolType {

    @XmlElement(required = true)
    protected String realm;
    @XmlElement(required = true)
    @XmlSchemaType(name = "anyURI")
    protected String issuer;
    @XmlElement(required = true)
    protected String roleDelimiter;
    @XmlElement(required = true)
    protected String roleURI;
    @XmlElement(required = true)
    protected AuthenticationType authenticationType;
    @XmlElement(required = true)
    protected HomeRealm homeRealm;
    @XmlElement(required = true)
    protected String freshness;
    @XmlElement(required = true)
    protected String reply;
    @XmlElement(required = true)
    protected String request;
    @XmlElement(required = true)
    protected ClaimTypesRequested claimTypesRequested;
    @XmlElement(required = true)
    protected List<String> securityTokenValidators;
    @XmlAttribute(name = "version", required = true)
    protected String version;

    /**
     * Gets the value of the realm property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getRealm() {
        return realm;
    }

    /**
     * Sets the value of the realm property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setRealm(String value) {
        this.realm = value;
    }

    /**
     * Gets the value of the issuer property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getIssuer() {
        return issuer;
    }

    /**
     * Sets the value of the issuer property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setIssuer(String value) {
        this.issuer = value;
    }

    /**
     * Gets the value of the roleDelimiter property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getRoleDelimiter() {
        return roleDelimiter;
    }

    /**
     * Sets the value of the roleDelimiter property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setRoleDelimiter(String value) {
        this.roleDelimiter = value;
    }

    /**
     * Gets the value of the roleURI property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getRoleURI() {
        return roleURI;
    }

    /**
     * Sets the value of the roleURI property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setRoleURI(String value) {
        this.roleURI = value;
    }

    /**
     * Gets the value of the authenticationType property.
     * 
     * @return possible object is {@link AuthenticationType }
     * 
     */
    public AuthenticationType getAuthenticationType() {
        return authenticationType;
    }

    /**
     * Sets the value of the authenticationType property.
     * 
     * @param value
     *            allowed object is {@link AuthenticationType }
     * 
     */
    public void setAuthenticationType(AuthenticationType value) {
        this.authenticationType = value;
    }

    /**
     * Gets the value of the homeRealm property.
     * 
     * @return possible object is {@link HomeRealm }
     * 
     */
    public HomeRealm getHomeRealm() {
        return homeRealm;
    }

    /**
     * Sets the value of the homeRealm property.
     * 
     * @param value
     *            allowed object is {@link HomeRealm }
     * 
     */
    public void setHomeRealm(HomeRealm value) {
        this.homeRealm = value;
    }

    /**
     * Gets the value of the freshness property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getFreshness() {
        return freshness;
    }

    /**
     * Sets the value of the freshness property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setFreshness(String value) {
        this.freshness = value;
    }

    /**
     * Gets the value of the reply property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getReply() {
        return reply;
    }

    /**
     * Sets the value of the reply property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setReply(String value) {
        this.reply = value;
    }

    /**
     * Gets the value of the request property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getRequest() {
        return request;
    }

    /**
     * Sets the value of the request property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setRequest(String value) {
        this.request = value;
    }

    /**
     * Gets the value of the claimTypesRequested property.
     * 
     * @return possible object is {@link ClaimTypesRequested }
     * 
     */
    public ClaimTypesRequested getClaimTypesRequested() {
        return claimTypesRequested;
    }

    /**
     * Sets the value of the claimTypesRequested property.
     * 
     * @param value
     *            allowed object is {@link ClaimTypesRequested }
     * 
     */
    public void setClaimTypesRequested(ClaimTypesRequested value) {
        this.claimTypesRequested = value;
    }

    /**
     * Gets the value of the securityTokenValidators property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a
     * snapshot. Therefore any modification you make to the returned list will
     * be present inside the JAXB object. This is why there is not a
     * <CODE>set</CODE> method for the securityTokenValidators property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getSecurityTokenValidators().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list {@link String }
     * 
     * 
     */
    public List<String> getSecurityTokenValidators() {
        if (securityTokenValidators == null) {
            securityTokenValidators = new ArrayList<String>();
        }
        return this.securityTokenValidators;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setVersion(String value) {
        this.version = value;
    }

}
