//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.28 at 02:33:06 PM CEST 
//

package org.apache.cxf.fediz.core.config;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}audienceUris"/>
 *         &lt;element ref="{}certificateValidation"/>
 *         &lt;element ref="{}trustedIssuers"/>
 *         &lt;element ref="{}maximumClockSkew"/>
 *         &lt;element ref="{}serviceCertificate"/>
 *         &lt;element ref="{}protocol"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "audienceUris", "certificateValidation",
        "trustedIssuers", "maximumClockSkew", "serviceCertificate", "protocol" })
@XmlRootElement(name = "contextConfig")
public class ContextConfig {

    @XmlElement(required = true)
    protected AudienceUris audienceUris;
    @XmlElement(required = true)
    protected ValidationType certificateValidation;
    @XmlElement(required = true)
    protected TrustedIssuers trustedIssuers;
    @XmlElement(required = true)
    protected BigInteger maximumClockSkew;
    @XmlElement(required = true)
    protected TrustManagersType serviceCertificate;
    @XmlElement(required = true)
    protected ProtocolType protocol;
    @XmlAttribute(name = "name", required = true)
    protected String name;

    /**
     * Gets the value of the audienceUris property.
     * 
     * @return possible object is {@link AudienceUris }
     * 
     */
    public AudienceUris getAudienceUris() {
        return audienceUris;
    }

    /**
     * Sets the value of the audienceUris property.
     * 
     * @param value
     *            allowed object is {@link AudienceUris }
     * 
     */
    public void setAudienceUris(AudienceUris value) {
        this.audienceUris = value;
    }

    /**
     * Gets the value of the certificateValidation property.
     * 
     * @return possible object is {@link ValidationType }
     * 
     */
    public ValidationType getCertificateValidation() {
        return certificateValidation;
    }

    /**
     * Sets the value of the certificateValidation property.
     * 
     * @param value
     *            allowed object is {@link ValidationType }
     * 
     */
    public void setCertificateValidation(ValidationType value) {
        this.certificateValidation = value;
    }

    /**
     * Gets the value of the trustedIssuers property.
     * 
     * @return possible object is {@link TrustedIssuers }
     * 
     */
    public TrustedIssuers getTrustedIssuers() {
        return trustedIssuers;
    }

    /**
     * Sets the value of the trustedIssuers property.
     * 
     * @param value
     *            allowed object is {@link TrustedIssuers }
     * 
     */
    public void setTrustedIssuers(TrustedIssuers value) {
        this.trustedIssuers = value;
    }

    /**
     * Gets the value of the maximumClockSkew property.
     * 
     * @return possible object is {@link BigInteger }
     * 
     */
    public BigInteger getMaximumClockSkew() {
        return maximumClockSkew;
    }

    /**
     * Sets the value of the maximumClockSkew property.
     * 
     * @param value
     *            allowed object is {@link BigInteger }
     * 
     */
    public void setMaximumClockSkew(BigInteger value) {
        this.maximumClockSkew = value;
    }

    /**
     * Gets the value of the serviceCertificate property.
     * 
     * @return possible object is {@link TrustManagersType }
     * 
     */
    public TrustManagersType getServiceCertificate() {
        return serviceCertificate;
    }

    /**
     * Sets the value of the serviceCertificate property.
     * 
     * @param value
     *            allowed object is {@link TrustManagersType }
     * 
     */
    public void setServiceCertificate(TrustManagersType value) {
        this.serviceCertificate = value;
    }

    /**
     * Gets the value of the protocol property.
     * 
     * @return possible object is {@link ProtocolType }
     * 
     */
    public ProtocolType getProtocol() {
        return protocol;
    }

    /**
     * Sets the value of the protocol property.
     * 
     * @param value
     *            allowed object is {@link ProtocolType }
     * 
     */
    public void setProtocol(ProtocolType value) {
        this.protocol = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setName(String value) {
        this.name = value;
    }

}
