//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.28 at 02:33:06 PM CEST 
//

package org.apache.cxf.fediz.core.config;

import java.math.BigInteger;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

/**
 * This object contains factory methods for each Java content interface and Java
 * element interface generated in the org.apache.cxf.fediz.core.config package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the
 * Java representation for XML content. The Java representation of XML content
 * can consist of schema derived interfaces and classes representing the binding
 * of schema type definitions, element declarations and model groups. Factory
 * methods for each of these are provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _RoleURI_QNAME = new QName("", "roleURI");
    private final static QName _Protocol_QNAME = new QName("", "protocol");
    private final static QName _CertificateValidation_QNAME = new QName("",
            "certificateValidation");
    private final static QName _MaximumClockSkew_QNAME = new QName("",
            "maximumClockSkew");
    private final static QName _TrustedIssuerItem_QNAME = new QName("",
            "trustedIssuerItem");
    private final static QName _ServiceCertificate_QNAME = new QName("",
            "serviceCertificate");
    private final static QName _RoleDelimiter_QNAME = new QName("",
            "roleDelimiter");
    private final static QName _Issuer_QNAME = new QName("", "issuer");
    private final static QName _SecurityTokenValidators_QNAME = new QName("",
            "securityTokenValidators");
    private final static QName _Realm_QNAME = new QName("", "realm");
    private final static QName _Request_QNAME = new QName("", "request");
    private final static QName _Reply_QNAME = new QName("", "reply");
    private final static QName _Freshness_QNAME = new QName("", "freshness");
    private final static QName _AudienceItem_QNAME = new QName("",
            "audienceItem");

    /**
     * Create a new ObjectFactory that can be used to create new instances of
     * schema derived classes for package: org.apache.cxf.fediz.core.config
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ContextConfig }
     * 
     */
    public ContextConfig createContextConfig() {
        return new ContextConfig();
    }

    /**
     * Create an instance of {@link AudienceUris }
     * 
     */
    public AudienceUris createAudienceUris() {
        return new AudienceUris();
    }

    /**
     * Create an instance of {@link TrustedIssuers }
     * 
     */
    public TrustedIssuers createTrustedIssuers() {
        return new TrustedIssuers();
    }

    /**
     * Create an instance of {@link TrustManagersType }
     * 
     */
    public TrustManagersType createTrustManagersType() {
        return new TrustManagersType();
    }

    /**
     * Create an instance of {@link HomeRealm }
     * 
     */
    public HomeRealm createHomeRealm() {
        return new HomeRealm();
    }

    /**
     * Create an instance of {@link AuthenticationType }
     * 
     */
    public AuthenticationType createAuthenticationType() {
        return new AuthenticationType();
    }

    /**
     * Create an instance of {@link ClaimTypesRequested }
     * 
     */
    public ClaimTypesRequested createClaimTypesRequested() {
        return new ClaimTypesRequested();
    }

    /**
     * Create an instance of {@link ClaimType }
     * 
     */
    public ClaimType createClaimType() {
        return new ClaimType();
    }

    /**
     * Create an instance of {@link FedizConfig }
     * 
     */
    public FedizConfig createFedizConfig() {
        return new FedizConfig();
    }

    /**
     * Create an instance of {@link CertStoreType }
     * 
     */
    public CertStoreType createCertStoreType() {
        return new CertStoreType();
    }

    /**
     * Create an instance of {@link KeyStoreType }
     * 
     */
    public KeyStoreType createKeyStoreType() {
        return new KeyStoreType();
    }

    /**
     * Create an instance of {@link FederationProtocolType }
     * 
     */
    public FederationProtocolType createFederationProtocolType() {
        return new FederationProtocolType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     */
    @XmlElementDecl(namespace = "", name = "roleURI")
    public JAXBElement<String> createRoleURI(String value) {
        return new JAXBElement<String>(_RoleURI_QNAME, String.class, null,
                value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ProtocolType }
     * {@code >}
     * 
     */
    @XmlElementDecl(namespace = "", name = "protocol")
    public JAXBElement<ProtocolType> createProtocol(ProtocolType value) {
        return new JAXBElement<ProtocolType>(_Protocol_QNAME,
                ProtocolType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ValidationType }
     * {@code >}
     * 
     */
    @XmlElementDecl(namespace = "", name = "certificateValidation")
    public JAXBElement<ValidationType> createCertificateValidation(
            ValidationType value) {
        return new JAXBElement<ValidationType>(_CertificateValidation_QNAME,
                ValidationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }
     * {@code >}
     * 
     */
    @XmlElementDecl(namespace = "", name = "maximumClockSkew")
    public JAXBElement<BigInteger> createMaximumClockSkew(BigInteger value) {
        return new JAXBElement<BigInteger>(_MaximumClockSkew_QNAME,
                BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}
     * {@link TrustManagersType }{@code >}
     * 
     */
    @XmlElementDecl(namespace = "", name = "trustedIssuerItem")
    public JAXBElement<TrustManagersType> createTrustedIssuerItem(
            TrustManagersType value) {
        return new JAXBElement<TrustManagersType>(_TrustedIssuerItem_QNAME,
                TrustManagersType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}
     * {@link TrustManagersType }{@code >}
     * 
     */
    @XmlElementDecl(namespace = "", name = "serviceCertificate")
    public JAXBElement<TrustManagersType> createServiceCertificate(
            TrustManagersType value) {
        return new JAXBElement<TrustManagersType>(_ServiceCertificate_QNAME,
                TrustManagersType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     */
    @XmlElementDecl(namespace = "", name = "roleDelimiter")
    public JAXBElement<String> createRoleDelimiter(String value) {
        return new JAXBElement<String>(_RoleDelimiter_QNAME, String.class,
                null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     */
    @XmlElementDecl(namespace = "", name = "issuer")
    public JAXBElement<String> createIssuer(String value) {
        return new JAXBElement<String>(_Issuer_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     */
    @XmlElementDecl(namespace = "", name = "securityTokenValidators")
    public JAXBElement<String> createSecurityTokenValidators(String value) {
        return new JAXBElement<String>(_SecurityTokenValidators_QNAME,
                String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     */
    @XmlElementDecl(namespace = "", name = "realm")
    public JAXBElement<String> createRealm(String value) {
        return new JAXBElement<String>(_Realm_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     */
    @XmlElementDecl(namespace = "", name = "request")
    public JAXBElement<String> createRequest(String value) {
        return new JAXBElement<String>(_Request_QNAME, String.class, null,
                value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     */
    @XmlElementDecl(namespace = "", name = "reply")
    public JAXBElement<String> createReply(String value) {
        return new JAXBElement<String>(_Reply_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     */
    @XmlElementDecl(namespace = "", name = "freshness")
    public JAXBElement<String> createFreshness(String value) {
        return new JAXBElement<String>(_Freshness_QNAME, String.class, null,
                value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     */
    @XmlElementDecl(namespace = "", name = "audienceItem")
    public JAXBElement<String> createAudienceItem(String value) {
        return new JAXBElement<String>(_AudienceItem_QNAME, String.class, null,
                value);
    }

}
